Presentation/SiC.Web/Models/PaymentRegistration/IndexViewModel.cs
namespace Nagnoi.SiC.Web.Models.PaymentRegistration
{
    #region References

    using System.Collections.Generic;
    using System.Web.Mvc;
    using Infrastructure.Web.ViewModels;

    #endregion

    public class IndexViewModel : BaseViewModel
    {
        #region Constructor

        public IndexViewModel()
        {
            CompensationRegions = new List<SelectListItem>();
            GroupedCompensationRegions = new List<SelectListItem>();
        }

        #endregion

        #region Properties

        public CaseViewModel CaseModel = new CaseViewModel();

        public IEnumerable<SelectListItem> CompensationRegions { get; set; }

        public IEnumerable<SelectListItem> GroupedCompensationRegions { get; set; }

        #endregion
    }
}

Presentation/SiC.Web/Models/PaymentRegistration/IppDesgloseCreateModel.cs
namespace Nagnoi.SiC.Web.Models.PaymentRegistration
{
    public class IppDesgloseCreateModel
    {
        #region Properties

        public int CompensationRegionId { get; set; }

        public decimal Percent { get; set; }

        public int Weeks { get; set; }

        #endregion
    }
}

Presentation/SiC.Web/Controllers/CaseController.cs
namespace Nagnoi.SiC.Web.Controllers
{
    #region References

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using CDI.WebApplication.DataTables.Result;
    using Infrastructure.Core.Helpers;
    using Domain.Core.Model;
    using Infrastructure.Web.Controllers;
    using Models.Case;
    using Models.Paging;
    using X.PagedList;

    #endregion
    
    public class CaseController : BaseController
    {
        #region Actions

        [HttpGet]
        public ActionResult SearchBox()
        {
            var model = new SearchViewModel();

            return PartialView("~/Views/Case/_SearchBox.cshtml", model.Rebuild(model));
        }

        [HttpPost]
        public JsonResult Search(DataTableParamCase param)
        {
            var cases = CaseService.SearchCaseDetails(param.CaseNumber, param.CaseKey, param.EntityName, param.SocialSecurityNumber, param.BirthDate, param.FilingDate, param.RegionId, param.ClinicId, param.EBTNumber)
                .OrderBy(m=>m.CaseId)                   
                .ToPagedList(param.Start + 1, param.Length);

            var data = CaseViewModel.CreateFrom(cases).ToList();

            var result = new DataTableResult<CaseViewModel>
            {
                draw = param.Draw,
                data = data,
                recordsFiltered = cases.Count,
                recordsTotal = cases.TotalItemCount
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("case/GetBalance/{caseDetailId}")]
        public JsonResult GetBalance(int caseDetailId)
        {
            var balance = TransactionService.GetBalanceByCase(caseDetailId);
            
            return Json(balance.GetValueOrDefault(decimal.Zero), JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        [Route("case/GetCaseDetailById/{caseDetailId}")]
        public JsonResult GetCaseDetailById(int caseDetailId)
        {
            var caseDetail = CaseService.FindCaseDetailById(caseDetailId);
            var caseMain = CaseService.FindCaseDetailByIdAndKey(caseDetail.CaseId.Value, "00");

            var balanceBeneficiario = TransactionService.GetBalanceByCase(caseDetailId);
            var balanceLesionado = TransactionService.GetBalanceByCase(caseMain.CaseDetailId);

            var model = CaseViewModel.CreateFrom(caseDetail, balanceBeneficiario.GetValueOrDefault(decimal.Zero), caseMain, balanceLesionado.GetValueOrDefault(decimal.Zero));

            return Json(new BasicDataTablesResult(model), JsonRequestBehavior.AllowGet);
        }

        #endregion

        [HttpGet]
        public ActionResult Index()
        {
            return View("Index", "_CaseLayout");
        }
        
        [HttpGet]
        public ActionResult Resumen(int? caseId)
        {
            InformacionCaso_Result model = CaseService.InformacionCaso(caseId).First();

            ViewBag.caseFolderId = caseId;

            ViewBag.caseNumber = model.CaseNumber;

            return View("Resumen", "_CaseLayout", model);
        }

        [HttpGet]
        public ActionResult ResumenTab(int? id)
        {

            //CaseWebservice.WsSessionEJBEndPointClient service = new CaseWebservice.WsSessionEJBEndPointClient();

            //service.ClientCredentials.UserName.UserName  = "SONORA";
            //service.ClientCredentials.UserName.Password = "ExpCASE2011";

            //var query = new doQueryByName();
            //query.String_1 = "GetCaseNumberByCaseId";
            
            //FieldPropertiesTO props = new FieldPropertiesTO();
            //props.stringValue = id;

            //query.arrayOfFieldPropertiesTO_2 = new FieldPropertiesTO[1];
            //query.arrayOfFieldPropertiesTO_2[0] = props;

            //FmsRowSetTO result = service.doQueryByName(query)[0];

            //var caseFolderId = result.resultRows.First().fieldList[0].stringValue;
            try
            {


                //String caseNumber = sif.GetCaseNumber(Int32.Parse(id)).First();
              

                InformacionCaso_Result datos = CaseService.InformacionCaso(id).First();

                datos.ReportLink = String.Format(SettingService.GetSettingValueByName("PaymentHistory.ReportLink"), datos.CaseNumber);
                
                if (!datos.IsNull())
                {
                    ViewBag.caseFolderId = id;
                    ViewBag.caseNumber = datos.CaseNumber;

                    return View("ResumenTab", "_CaseLayout", datos);
                }
                else
                {
                    ViewBag.caseFolderId = id;
                    return View("_SinDatos", "_CaseLayout");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ViewBag.caseFolderId = id;
                return View("_SinDatos", "_CaseLayout");
            }
        }

        [HttpGet]
        [Route("Case/CertificationTab/{caseFolderId}")]
        public ActionResult CertificationTab(string caseFolderId)
        {
            var model = new Nagnoi.SiC.Web.Models.PaymentCertification.CertificationViewModel();

            int id = Convert.ToInt32(caseFolderId);
            InformacionCaso_Result caseData = CaseService.InformacionCaso(id).First();

            ViewBag.CaseNumber = caseData.CaseNumber;
            ViewBag.CaseKey = null;
            
            model.Status = GetAllStatus();
            model.Concept = GetAllConcept();
            return View("CertificationTab", "_CaseLayout", model);
        }

        public JsonResult GetAllConcept()
        {
            IList<Object> lstConcepts = new List<Object>();
            var concept = PaymentService.GetAllConcepts();

            foreach (var c in concept)
            {
                if (c.ConceptType != "NA")
                {
                    lstConcepts.Add(new { label = c.Concept1, value = c.Concept1 });
                }
            }

            return Json(lstConcepts, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllStatus()
        {
            IList<Object> lstStatus = new List<Object>();
            var status = PaymentService.GetAllPaymentStatuses();
            foreach (var s in status)
            {
                if (s.StatusCode == "D")
                {
                    lstStatus.Add(new { label = s.Status1, value = s.Status1 });
                }
            }
            return Json(lstStatus, JsonRequestBehavior.AllowGet);
        }
    }
}

Presentation/SiC.Web/Controllers/PaymentRegistrationController.cs
namespace Nagnoi.SiC.Web.Controllers
{
    #region References

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using CDI.WebApplication.DataTables.Result;
    using Domain.Core.Model;
    using Infrastructure.Core.Helpers;
    using Infrastructure.Web.Controllers;
    using Infrastructure.Web.Helpers;
    using Infrastructure.Web.Utilities;
    using Models;
    using Models.PaymentRegistration;
    using Newtonsoft.Json;

    #endregion
    
    public class PaymentRegistrationController : BaseController
    {
        #region Actions

        [HttpGet]
        public ActionResult Index()
        {
            var model = new IndexViewModel();

            var allCompensationRegions = CompensationRegionService.GetAllCompensationRegions();
            var groupedCompensationRegions = CompensationRegionService.GetCompensationRegionsGroupedByRegion();

            model.CompensationRegions = allCompensationRegions.ToSelectList(c => c.Code, c => string.Format("{0}|{1}|{2}|{3}|{4}", c.Code, c.Region, c.SubRegion, c.Weeks, c.CompensationRegionId), null, "Seleccionar");
            model.GroupedCompensationRegions = groupedCompensationRegions.ToSelectList(c => c.Region, c => c.Region, null, "Seleccionar");

            return View(model);
        }

        [HttpPost]
        public JsonResult InsertInvestment(int caseId, int caseDetailId, DateTime? fechadecision, string payments, string comment, string caseNumber, int beneficiario)
        {
            DateTime workingDate = DateTime.Now;

            var currentCase = CaseService.FindCaseByNumber(caseNumber);

            var transaction = new Transaction
            {
                CaseDetailId = caseDetailId,
                TransactionTypeId = (int) TransactionTypeEnum.Inversion,
                TransactionDate = workingDate,
                TransactionAmount = decimal.Zero,
                Comment = comment
            };

            TransactionService.CreateTransaction(transaction);

           
            var amount = decimal.Zero;

            var serializedPayments = JsonConvert.DeserializeObject<List<PaymentTransaction>>(payments);
            foreach (var serializedPayment in serializedPayments)
            {
                var entidad = new Entity
                {
                    FullName = serializedPayment.Entidad,
                    SourceId = 9
                };
                EntityService.CreateEntity(entidad);

                var payment = new Payment
                {
                    CaseId = caseId,
                    CaseDetailId = caseDetailId,
                    TransactionId = transaction.TransactionId,
                    CaseNumber = caseNumber,
                    ConceptId = currentCase.ConceptId.Value,
                    ClassId = 3,
                    Amount = serializedPayment.Inversion,
                    EntityId_RemitTo = entidad.EntityId,
                    Remitter = entidad,
                    ToDate = fechadecision,
                    TransactionNum = transaction.TransactionId.ToString().PadLeft(9, '0'),
                    CheckBk = 0,
                    StatusId = 12,
                    IssueDate = workingDate,
                    StatusChangeDate = workingDate
                };
                amount += serializedPayment.Inversion.Value;

                PaymentService.CreatePayment(payment);
            }

            transaction.TransactionAmount = amount;

            TransactionService.ModifyTransaction(transaction);

            return Json(new BasicDataTablesResult(new { Status = "OK" }));
        }

        [HttpPost]
        public JsonResult InsertPeremptory(int caseId, int caseDetailId, int entityid, decimal? cantidad, int beneficiario, string comment, string caseNumber)
        {
            DateTime workingDate = DateTime.Now;

            var transaction = new Transaction
            {
                CaseDetailId = caseDetailId,
                TransactionTypeId = (int) TransactionTypeEnum.Anticipos,
                TransactionDate = workingDate,
                TransactionAmount = cantidad,
                Comment = comment
            };
            TransactionService.CreateTransaction(transaction);

            var payment = new Payment
            {
                CaseId = caseId,
                CaseDetailId = caseDetailId,
                TransactionId = transaction.TransactionId,
                CaseNumber = caseNumber,
                ConceptId = 2,
                ClassId = 2,
                Amount = cantidad,
                TransactionNum = transaction.TransactionId.ToString().PadLeft(9, '0'),
                StatusId = 12,
                IssueDate = workingDate,
                StatusChangeDate = workingDate            
            };
            PaymentService.CreatePayment(payment);

            return Json(new BasicDataTablesResult(new { Status = "OK" }));
        }

        [HttpPost]
        public JsonResult InsertPendingDiet(int caseId, int caseDetailId, DateTime? fechadecision, DateTime? fechavisita,
            DateTime? fechanotificacion, string numerocaso, decimal? montototal, string periods, string comment, string caseNumber)
        {
            CaseDetail currentCase = CaseService.FindCaseDetailById(caseDetailId);

            DateTime workingDate = DateTime.Now;

            var transaction = new Transaction()
            {
                CaseDetailId = caseDetailId,
                TransactionTypeId = (int) TransactionTypeEnum.Retroactivo,
                TransactionAmount = montototal,
                Comment = comment,
                TransactionDate = workingDate,
                ICCaseNumber = numerocaso,
                NotificationDateIC = fechanotificacion,
                HearingDateIC = fechavisita
            };

            TransactionService.CreateTransaction(transaction);

            var serializedPeriods = JsonConvert.DeserializeObject<List<PeriodDiet>>(periods);

            foreach (var period in serializedPeriods)
            {
                short totalDays = Common.GetBusinessDays(period.Desde, period.Hasta, currentCase.Case.DaysWeek.GetValueOrDefault(0));
                
                var payment = new Payment()
                {
                    CaseId = caseId,
                    CaseDetailId = caseDetailId,
                    CaseNumber = caseNumber,
                    TransactionId = transaction.TransactionId,
                    ConceptId = 2,
                    ClassId = 11,
                    Amount = montototal,
                    StatusId = 12,
                    IssueDate = fechadecision,
                    StatusChangeDate = workingDate,
                    FromDate = period.Desde,
                    ToDate = period.Hasta,
                    Discount = period.Descuento,
                    PaymentDay = totalDays
                };

                PaymentService.CreatePayment(payment);
            }
            
            return Json(new BasicDataTablesResult(new { Status = "OK" }));
        }

        [HttpPost]
        public JsonResult InsertHonoraryLawyer(int caseId, int caseDetailId, DateTime? fechadecision, DateTime? fechavisita,
            DateTime? fechanotificacion, string numerocaso, decimal? montototal, string comment, string caseNumber)
        {
            DateTime workingDate = DateTime.Now;

            var transaction = new Transaction()
            {
                CaseDetailId = caseDetailId,
                TransactionTypeId = (int)TransactionTypeEnum.HonorarioAbogados,
                TransactionAmount = montototal,
                Comment = comment,
                DecisionDate = fechadecision,
                TransactionDate = workingDate,
                ICCaseNumber = numerocaso,
                NotificationDateIC = fechanotificacion,
                HearingDateIC = fechavisita
            };
            TransactionService.CreateTransaction(transaction);

            var payment = new Payment
            {
                CaseId = caseId,
                CaseDetailId = caseDetailId,
                TransactionId = transaction.TransactionId,
                CaseNumber = caseNumber,
                ConceptId = 1,
                ClassId = 8,
                Amount = montototal,
                TransactionNum = transaction.TransactionId.ToString().PadLeft(9, '0'),
                StatusId = 12,
                IssueDate = workingDate,
                StatusChangeDate = workingDate
            };
            PaymentService.CreatePayment(payment);

            return Json(new BasicDataTablesResult(new { Status = "OK" }));
        }

        [HttpPost]
        public JsonResult InsertIpp(IppCreateModel model)
        {
            DateTime workingDate = DateTime.Now;

            var transaction = new Transaction()
            {
                CaseDetailId = model.CaseDetailId,
                TransactionTypeId = (int)TransactionTypeEnum.AdjudicacionAdicional,
                TransactionAmount = model.CantidadAdjudicada,
                MonthlyInstallment = model.Mensualidad,
                NumberOfWeeks = model.Semanas,
                DecisionDate = model.FechaAdjudicacion,
                TransactionDate = workingDate,
                Comment = model.Comments,
                ConceptId = 3
            };

            foreach (var desglose in model.Desgloses)
            {
                transaction.TransactionDetails.Add(new TransactionDetail
                {
                    CompensationRegionId = desglose.CompensationRegionId,
                    Percent = desglose.Percent,
                    Amount = desglose.Percent * desglose.Weeks * model.CompSemanalInca
                });
            }
            TransactionService.CreateTransaction(transaction);
            
            var payment = new Payment
            {
                CaseId = model.CaseId,

Presentation/SiC.Web/Views/PaymentRegistration/Index.cshtml
@model Nagnoi.SiC.Web.Models.PaymentRegistration.IndexViewModel

@{
    ViewBag.Title = "Registro de Pago";
}

@section Styles{
    @Styles.Render("~/bundles/datepicker/css")
}

<div class="homePage">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header text-danger">
                <h3>Registro de Pagos</h3>
            </div>
        </div>
    </div>
    @{
        Html.RenderAction("SearchBox", "Case");
    }
    <div id="header-panel" class="row hidden">
        <div class="col-md-12">
            <h3>
                Forma de Pagos
            </h3>
            <hr />
            <div class="panel-group" role="tablist">
                @Html.Partial("_HeaderCase", Model.CaseModel)
                <div id="doc-class-panel" class="panel panel-default">
                    <div class="panel-heading" role="tab">
                        <div class="panel-title">
                            <strong class="text-danger">
                                @Model.ResourceService.GetResourceString("HeaderCaso.ClaseDocumento.label.text")
                            </strong>
                        </div>
                    </div>
                    <div class="panel-collapse collapse in" role="tabpanel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="ddlDocumentType"></label>
                                        <select id="ddlDocumentType" name="ddlDocumentType" class="form-control">
                                            <option value="">-- Seleccionar --</option>
                                            <option value="1">Inversión</option>
                                            <option value="2">IPP</option>
                                            <option value="3">Gastos perentorios</option>
                                            <option value="4">Dietas Pendientes</option>
                                            <option value="5">Honorarios de Abogados</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="payment-per-panel" class="panel-group hidden" role="tablist">
                @Html.Partial("_PaymentPeremptory")
            </div>
            <div id="payment-inv-panel" class="panel-group hidden" role="tablist">
                @Html.Partial("_PaymentInvestment")
            </div>
            <div id="payment-ipp-panel" class="panel-group hidden" role="tablist">
                @Html.Partial("_PaymentIpp", Model)
            </div>
            <div id="payment-diet-panel" class="panel-group hidden" role="tablist">
                @Html.Partial("_PaymentPendingDiet")
            </div>
            <div id="payment-lawyer-panel" class="panel-group hidden" role="tablist">
                @Html.Partial("_PaymentLawyer")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/Payments")
}

Presentation/SiC.Web/Views/PaymentRegistration/_PaymentIpp.cshtml
@using Nagnoi.SiC.Web.Models.PaymentRegistration

@model IndexViewModel

<div id="resumen" class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <strong class="text-danger">
                Resumen
            </strong>
            <div class="pull-right">
                <a class="collapse-click">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div class='table-responsive'>
                    <table id="tblIpp" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr class="active">
                                <th>
                                    @Model.ResourceService.GetResourceString("PagoIpp.FechaAdjudicacion.header.text")
                                </th>
                                <th>
                                    @Model.ResourceService.GetResourceString("PagoIpp.Semanas.label.text")
                                </th>
                                <th>
                                    Mensualidad
                                </th>
                                <th>
                                    @Model.ResourceService.GetResourceString("PagoIpp.CantidadAdjudicada.header.text")
                                </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="detalle" class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <strong class="text-danger">
                Detalle
            </strong>
            <div class="pull-right">
                <a class="collapse-click">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <form id="frmIpp" action="/" method="post">
            <fieldset>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label" for="ipp_fechaadjudicacion">
                                @Model.ResourceService.GetResourceString("PagoIpp.FechaAdjudicacion.label.text")
                            </label>
                            <div class='input-group date'>
                                <input type="text" class="form-control" id="ipp_fechaadjudicacion" name="ipp_fechaadjudicacion" readonly />
                                <label class="input-group-btn" for="ipp_fechaadjudicacion">
                                    <span class="btn btn-default">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </label>                                
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label" for="ipp_adjudicacionadicional">
                                Cantidad Adjudicada
                            </label>
                            <input class="form-control" id="ipp_adjudicacionadicional" name="ipp_adjudicacionadicional" type="text" maxlength="75" />
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label" for="ipp_semanas">
                                @Model.ResourceService.GetResourceString("PagoIpp.Semanas.label.text")
                            </label>
                            <label class="form-control" id="ipp_semanas"></label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label" for="ipp_mensualidad">
                                @Model.ResourceService.GetResourceString("PagoIpp.Mensualidad.label.text")
                            </label>
                            <label class="form-control" id="ipp_mensualidad"></label>
                        </div>
                    </div>
                </div>
                @{
                    @Html.Partial("_DesgloseIPP")                    
                }
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label" for="ipp_observaciones">
                                @Model.ResourceService.GetResourceString("PagoIpp.Observaciones.label.text")
                            </label>
                            <p>
                                <textarea class="form-control" rows="5" id="ipp_observaciones" name="ipp_observaciones" required></textarea>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-right">
            <input class="btn btn-success nuevo" type="button" value="Nuevo" />
            <input id="btnSaveIpp" class="btn btn-success" type="button" value="Guardar" />
            <input class="btn btn-success cancelar" type="button" value="Cancelar" />
        </div>
    </div>
</div>